#!/bin/sh
path=$(uci get uhttpd.main.home)"/"
echo "<root>" > $path"xml/networkSettings.xml"
echo "<item>" >> $path"xml/networkSettings.xml"
echo "<name>SSID (Name)</name>" >> $path"xml/networkSettings.xml"
echo "<value>" >> $path"xml/networkSettings.xml"
grep ssid /etc/config/wireless | awk '{print substr($3, 2, length($3) - 2)}' >> $path"xml/networkSettings.xml"
echo "</value>" >> $path"xml/networkSettings.xml"
echo "</item>" >> $path"xml/networkSettings.xml"
echo "<item>" >> $path"xml/networkSettings.xml"
echo "<name>Security Type</name>" >> $path"xml/networkSettings.xml"
echo "<value>" >> $path"xml/networkSettings.xml"
grep encryption /etc/config/wireless | awk '{print substr($3, 2, length($3) - 2)}' >> $path"xml/networkSettings.xml"
echo "</value>" >> $path"xml/networkSettings.xml"
echo "</item>" >> $path"xml/networkSettings.xml"
echo "<item>" >> $path"xml/networkSettings.xml"
echo "<name>Password</name>" >> $path"xml/networkSettings.xml"
echo "<value>" >> $path"xml/networkSettings.xml"
grep key /etc/config/wireless | awk '{print substr($3, 2, length($3) - 2)}' >> $path"xml/networkSettings.xml"
echo "</value>" >> $path"xml/networkSettings.xml"
echo "</item>" >> $path"xml/networkSettings.xml"
echo "<item>" >> $path"xml/networkSettings.xml"
echo "<name>Channel</name>" >> $path"xml/networkSettings.xml"
echo "<value>" >> $path"xml/networkSettings.xml"
grep channel /etc/config/wireless | awk '{print substr($3, 2, length($3) - 2)}' >> $path"xml/networkSettings.xml"
echo "</value>" >> $path"xml/networkSettings.xml"
echo "</item>" >> $path"xml/networkSettings.xml"
echo "</root>" >> $path"xml/networkSettings.xml"
echo "Success"

